#!/usr/bin/with-contenv bash

# application specific configurations
FILE=/config/www/invoiceplane/index.php
CONFIG_FILE=/config/www/invoiceplane/ipconfig.php
CURRENT_VERSION=$(grep -oP 'IP_VERSION=\K[^;]+' "$CONFIG_FILE" 2>/dev/null)

if [ -f "$FILE" ] && [ "$FORCE_UPDATE" != "true" ] && [ "$CURRENT_VERSION" == "$VERSION" ]; then
    echo "InvoicePlane Installation found and no update required";
else 
    echo "Setting up or updating InvoicePlane at /config/www/invoiceplane";
    
    # create our folders/files
    mkdir -p \
        /config/www/invoiceplane \
        /config/log/invoiceplane

    # install or update InvoicePlane with overwrite
    unzip -oq ${INVOICEPLANE_SRC} -d /config/www/invoiceplane

    touch /config/log/invoiceplane/{access,error}_invoiceplane_log

    # db config - only move if it's a fresh install
    mv /config/www/invoiceplane/ipconfig.php.example /config/www/invoiceplane/ipconfig.php

    # update variables
    sed -i "s/IP_URL=/IP_URL=${IP_URL//\//\\/}/g" $CONFIG_FILE
    sed -i "s/DB_HOSTNAME=/DB_HOSTNAME=${DB_HOSTNAME}/g" $CONFIG_FILE
    sed -i "s/DB_USERNAME=/DB_USERNAME=${DB_USERNAME}/g" $CONFIG_FILE
    sed -i "s/DB_PASSWORD=/DB_PASSWORD=${DB_PASSWORD}/g" $CONFIG_FILE
    sed -i "s/DB_DATABASE=/DB_DATABASE=${DB_DATABASE}/g" $CONFIG_FILE
    sed -i "s/DB_PORT=/DB_PORT=${DB_PORT}/g" $CONFIG_FILE
    sed -i "s/REMOVE_INDEXPHP=false/REMOVE_INDEXPHP=true/g" $CONFIG_FILE
    sed -i "s/IP_VERSION=[^;]*/IP_VERSION=$VERSION/g" $CONFIG_FILE
fi

# permissions
chown -R alpine:alpine \
    /config \
    /var/tmp/nginx \
    /config/www/invoiceplane

echo "Done!";
